/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowlerMicRouteImport } from './routes/howler-mic'
import { Route as ApiHowlerCommandRouteImport } from './routes/api/howler-command'
import { Route as ApiHowlerIntentRouteImport } from './routes/api/howler-intent'
import { Route as ApiHowlerSpeakRouteImport } from './routes/api/howler-speak'
import { Route as ApiHowlerStateRouteImport } from './routes/api/howler-state'
import { Route as ApiHowlerTraceRouteImport } from './routes/api/howler-trace'
import { Route as ApiHowlerWhereRouteImport } from './routes/api/howler-where'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as DrawTokenRouteImport } from './routes/draw.$token'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdModuleIdRouteImport } from './routes/projects.$projectId.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowlerMicRoute = HowlerMicRouteImport.update({
  id: '/howler-mic',
  path: '/howler-mic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHowlerCommandRoute = ApiHowlerCommandRouteImport.update({
  id: '/api/howler-command',
  path: '/api/howler-command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHowlerIntentRoute = ApiHowlerIntentRouteImport.update({
  id: '/api/howler-intent',
  path: '/api/howler-intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHowlerSpeakRoute = ApiHowlerSpeakRouteImport.update({
  id: '/api/howler-speak',
  path: '/api/howler-speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHowlerStateRoute = ApiHowlerStateRouteImport.update({
  id: '/api/howler-state',
  path: '/api/howler-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHowlerTraceRoute = ApiHowlerTraceRouteImport.update({
  id: '/api/howler-trace',
  path: '/api/howler-trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHowlerWhereRoute = ApiHowlerWhereRouteImport.update({
  id: '/api/howler-where',
  path: '/api/howler-where',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawTokenRoute = DrawTokenRouteImport.update({
  id: '/draw/$token',
  path: '/draw/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdModuleIdRoute =
  ProjectsProjectIdModuleIdRouteImport.update({
    id: '/projects/$projectId/$moduleId',
    path: '/projects/$projectId/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/howler-mic': typeof HowlerMicRoute
  '/api/howler-command': typeof ApiHowlerCommandRoute
  '/api/howler-intent': typeof ApiHowlerIntentRoute
  '/api/howler-speak': typeof ApiHowlerSpeakRoute
  '/api/howler-state': typeof ApiHowlerStateRoute
  '/api/howler-trace': typeof ApiHowlerTraceRoute
  '/api/howler-where': typeof ApiHowlerWhereRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/draw/$token': typeof DrawTokenRoute
  '/projects/$projectId/$moduleId': typeof ProjectsProjectIdModuleIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/howler-mic': typeof HowlerMicRoute
  '/api/howler-command': typeof ApiHowlerCommandRoute
  '/api/howler-intent': typeof ApiHowlerIntentRoute
  '/api/howler-speak': typeof ApiHowlerSpeakRoute
  '/api/howler-state': typeof ApiHowlerStateRoute
  '/api/howler-trace': typeof ApiHowlerTraceRoute
  '/api/howler-where': typeof ApiHowlerWhereRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/draw/$token': typeof DrawTokenRoute
  '/projects/$projectId/$moduleId': typeof ProjectsProjectIdModuleIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/howler-mic': typeof HowlerMicRoute
  '/api/howler-command': typeof ApiHowlerCommandRoute
  '/api/howler-intent': typeof ApiHowlerIntentRoute
  '/api/howler-speak': typeof ApiHowlerSpeakRoute
  '/api/howler-state': typeof ApiHowlerStateRoute
  '/api/howler-trace': typeof ApiHowlerTraceRoute
  '/api/howler-where': typeof ApiHowlerWhereRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/draw/$token': typeof DrawTokenRoute
  '/projects/$projectId/$moduleId': typeof ProjectsProjectIdModuleIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/howler-mic'
    | '/api/howler-command'
    | '/api/howler-intent'
    | '/api/howler-speak'
    | '/api/howler-state'
    | '/api/howler-trace'
    | '/api/howler-where'
    | '/api/rtc'
    | '/api/transcribe'
    | '/draw/$token'
    | '/projects/$projectId/$moduleId'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/howler-mic'
    | '/api/howler-command'
    | '/api/howler-intent'
    | '/api/howler-speak'
    | '/api/howler-state'
    | '/api/howler-trace'
    | '/api/howler-where'
    | '/api/rtc'
    | '/api/transcribe'
    | '/draw/$token'
    | '/projects/$projectId/$moduleId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/howler-mic'
    | '/api/howler-command'
    | '/api/howler-intent'
    | '/api/howler-speak'
    | '/api/howler-state'
    | '/api/howler-trace'
    | '/api/howler-where'
    | '/api/rtc'
    | '/api/transcribe'
    | '/draw/$token'
    | '/projects/$projectId/$moduleId'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowlerMicRoute: typeof HowlerMicRoute
  ApiHowlerCommandRoute: typeof ApiHowlerCommandRoute
  ApiHowlerIntentRoute: typeof ApiHowlerIntentRoute
  ApiHowlerSpeakRoute: typeof ApiHowlerSpeakRoute
  ApiHowlerStateRoute: typeof ApiHowlerStateRoute
  ApiHowlerTraceRoute: typeof ApiHowlerTraceRoute
  ApiHowlerWhereRoute: typeof ApiHowlerWhereRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  DrawTokenRoute: typeof DrawTokenRoute
  ProjectsProjectIdModuleIdRoute: typeof ProjectsProjectIdModuleIdRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howler-mic': {
      id: '/howler-mic'
      path: '/howler-mic'
      fullPath: '/howler-mic'
      preLoaderRoute: typeof HowlerMicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/howler-command': {
      id: '/api/howler-command'
      path: '/api/howler-command'
      fullPath: '/api/howler-command'
      preLoaderRoute: typeof ApiHowlerCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/howler-intent': {
      id: '/api/howler-intent'
      path: '/api/howler-intent'
      fullPath: '/api/howler-intent'
      preLoaderRoute: typeof ApiHowlerIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/howler-speak': {
      id: '/api/howler-speak'
      path: '/api/howler-speak'
      fullPath: '/api/howler-speak'
      preLoaderRoute: typeof ApiHowlerSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/howler-state': {
      id: '/api/howler-state'
      path: '/api/howler-state'
      fullPath: '/api/howler-state'
      preLoaderRoute: typeof ApiHowlerStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/howler-trace': {
      id: '/api/howler-trace'
      path: '/api/howler-trace'
      fullPath: '/api/howler-trace'
      preLoaderRoute: typeof ApiHowlerTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/howler-where': {
      id: '/api/howler-where'
      path: '/api/howler-where'
      fullPath: '/api/howler-where'
      preLoaderRoute: typeof ApiHowlerWhereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw/$token': {
      id: '/draw/$token'
      path: '/draw/$token'
      fullPath: '/draw/$token'
      preLoaderRoute: typeof DrawTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/$moduleId': {
      id: '/projects/$projectId/$moduleId'
      path: '/projects/$projectId/$moduleId'
      fullPath: '/projects/$projectId/$moduleId'
      preLoaderRoute: typeof ProjectsProjectIdModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowlerMicRoute: HowlerMicRoute,
  ApiHowlerCommandRoute: ApiHowlerCommandRoute,
  ApiHowlerIntentRoute: ApiHowlerIntentRoute,
  ApiHowlerSpeakRoute: ApiHowlerSpeakRoute,
  ApiHowlerStateRoute: ApiHowlerStateRoute,
  ApiHowlerTraceRoute: ApiHowlerTraceRoute,
  ApiHowlerWhereRoute: ApiHowlerWhereRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  DrawTokenRoute: DrawTokenRoute,
  ProjectsProjectIdModuleIdRoute: ProjectsProjectIdModuleIdRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
