import { type PortfolioState, type Project } from "./types";
import { deboardJob } from "./job";
import { tradewalkBlueprint } from "./tradewalk";
import { kfProjects } from "./kf-portfolio";
import { deboardFinancials } from "./client-budgets";
import { deboardSowScope } from "./sow";

function deboard(): Project {
  return {
    id: "deboard",
    name: "DeBoard Residence",
    clientName: "DeBoard",
    address: "227 Marengo Dr",
    projectType: "Detached garage + mower storage + conditioned second-floor office/flex + half bath",
    timezone: "America/New_York",
    revision: 21,
    healthBand: "YELLOW",
    paused: false,
    heldPhases: [],
    dashboardNote:
      "Sam concrete/site-prep expected complete Sat Sep 12. John Marr framing and Jason Bonham electrical are unconfirmed after pads.",
    officialStart: "2026-08-18",
    intendedFinish: null,
    sourceLabel: "KF Live PM Intelligence Dashboard — New Model v2 · observed 2026-09-11",
    activities: {
      "act-footer": {
        id: "act-footer",
        name: "Footer",
        phase: "Foundation",
        state: "COMPLETE",
        trade: "Concrete",
        durationLikely: 3,
        committedStart: "2026-08-18",
        committedFinish: "2026-08-20",
        actualStart: "2026-08-18",
        actualFinish: "2026-08-20",
        predecessorId: null,
        locked: true,
        notes: null,
      },
      "act-block": {
        id: "act-block",
        name: "Block walls",
        phase: "Foundation",
        state: "COMPLETE",
        trade: "Masonry",
        durationLikely: 5,
        committedStart: "2026-08-21",
        committedFinish: "2026-08-27",
        actualStart: "2026-08-21",
        actualFinish: "2026-08-27",
        predecessorId: "act-footer",
        locked: true,
        notes: null,
      },
      "act-concrete": {
        id: "act-concrete",
        name: "Concrete slab",
        phase: "Foundation",
        state: "IN_PROGRESS",
        trade: "Concrete",
        durationLikely: 4,
        committedStart: "2026-09-09",
        committedFinish: "2026-09-12",
        actualStart: "2026-09-09",
        actualFinish: null,
        predecessorId: "act-block",
        locked: false,
        notes: "KF working sequence: Sam mobilized Sep 9, expected complete Sat Sep 12. Confirm in the field — Howler will not mark complete from a target date.",
      },
      "act-framing": {
        id: "act-framing",
        name: "Framing / dry-in",
        phase: "Structure",
        state: "NOT_STARTED",
        trade: "Framing",
        durationLikely: 12,
        committedStart: "2026-09-14",
        committedFinish: null,
        actualStart: null,
        actualFinish: null,
        predecessorId: "act-concrete",
        locked: false,
        notes: "KF target Mon Sep 14 with John Marr. Confirmation pending. Jason Bonham electrical follow-on also unconfirmed.",
      },
      "act-roof": {
        id: "act-roof",
        name: "Roof",
        phase: "Envelope",
        state: "NOT_STARTED",
        trade: "Roofing",
        durationLikely: 5,
        committedStart: null,
        committedFinish: null,
        actualStart: null,
        actualFinish: null,
        predecessorId: "act-framing",
        locked: false,
        notes: null,
      },
      "act-mech": {
        id: "act-mech",
        name: "MEP rough-in",
        phase: "Systems",
        state: "NOT_STARTED",
        trade: "MEP",
        durationLikely: 8,
        committedStart: null,
        committedFinish: null,
        actualStart: null,
        actualFinish: null,
        predecessorId: "act-framing",
        locked: false,
        notes: null,
      },
      "act-cabinetry": {
        id: "act-cabinetry",
        name: "Cabinetry",
        phase: "Finishes",
        state: "NOT_STARTED",
        trade: "Cabinetry",
        durationLikely: 6,
        committedStart: null,
        committedFinish: null,
        actualStart: null,
        actualFinish: null,
        predecessorId: "act-mech",
        locked: false,
        notes: null,
      },
    },
    scopeItems: deboardSowScope(),
    financials: deboardFinancials(),
    blueprint: tradewalkBlueprint(),
    events: [
      {
        id: "evt-seed-19",
        revision: 19,
        type: "BUDGET_INGESTED",
        occurredAt: "2026-09-12T20:00:00.000Z",
        note: "Ingested Deboard Trade Budget & Estimate Tracker. Cost budget $165,552.28. Sell price $256,606.04 is not the trade baseline. Synthetic $400k retired.",
        clerical: true,
      },
      {
        id: "evt-seed-20",
        revision: 20,
        type: "DRAWING_LIBRARY_INGESTED",
        occurredAt: "2026-09-12T20:45:00.000Z",
        note: "Copied Drive originals into Howler (plans + SOW + rules) without deleting Drive. Carver progress now reads the full SOW, not leftover punch.",
        clerical: true,
      },
      {
        id: "evt-seed-21",
        revision: 21,
        type: "SOW_INGESTED",
        occurredAt: "2026-09-12T21:10:00.000Z",
        note: "Deboard / Carver / Ciurlizza / McMillan SOW and drawing copies stored in Howler. Drive originals untouched.",
        clerical: true,
      },
    ],
    job: deboardJob(),
  };
}

export const SEED_VERSION = "howler-pilot-v15-dashboard-8-2026-09-13";

export function createSeedState(): PortfolioState {
  return {
    projects: {
      "deboard": deboard(),
      ...kfProjects(),
    },
  };
}
