import type {
  ConstraintReadinessV094,
  ProjectModelV094,
} from "../domain/types";

const dt = "2026-08-26T18:00:00-04:00";
const w = (
  optimistic: string,
  likely: string,
  conservative: string,
): ConstraintReadinessV094 => ({ optimistic, likely, conservative });

export function createDeboardSeed(): ProjectModelV094 {
  const projectId = "deboard-v091";
  const sources = {
    "src-plans": {
      id: "src-plans",
      type: "PLAN",
      label: "DeBoard Tradewalk Plans - June 12, 2025",
      observedAt: dt,
      authority: 0.9,
      reliability: 0.85,
    },
    "src-scope": {
      id: "src-scope",
      type: "SCOPE",
      label:
        "Scope of Work and Rules - includes Footer -> Block -> Framing dry-in -> slab sequence",
      observedAt: dt,
      authority: 0.95,
      reliability: 0.9,
    },
    "src-engineering": {
      id: "src-engineering",
      type: "ENGINEERING",
      label: "DeBoard LVL calculations - Aug 17, 2026",
      observedAt: dt,
      authority: 0.98,
      reliability: 0.95,
    },
    "src-budget": {
      id: "src-budget",
      type: "BUDGET",
      label: "DeBoard Trade Budget & Estimate Tracker",
      observedAt: dt,
      authority: 0.85,
      reliability: 0.8,
    },
    "src-dashboard": {
      id: "src-dashboard",
      type: "PM_INPUT",
      label: "KF Live PM Intelligence Dashboard - DeBoard current status",
      observedAt: dt,
      authority: 0.9,
      reliability: 0.9,
    },
    "src-building-package": {
      id: "src-building-package",
      type: "CALENDAR",
      label:
        "Walls/subfloor building package committed for Aug 28; receipt still requires field verification",
      observedAt: dt,
      effectiveDate: "2026-08-28",
      authority: 0.9,
      reliability: 0.9,
    },
    "src-roof-action": {
      id: "src-roof-action",
      type: "CALENDAR",
      label: "Roof package vendor analysis / Tony - Aug 26",
      observedAt: dt,
      effectiveDate: "2026-08-26",
      authority: 0.8,
      reliability: 0.85,
    },
    "src-masonry-calendar": {
      id: "src-masonry-calendar",
      type: "CALENDAR",
      label:
        "Prior masonry target Aug 24; no independent field start verification attached",
      observedAt: dt,
      effectiveDate: "2026-08-24",
      authority: 0.65,
      reliability: 0.65,
    },
    "src-hvac": {
      id: "src-hvac",
      type: "ESTIMATE",
      label: "Revised multi-zone mini-split - $7,366",
      observedAt: dt,
      authority: 0.9,
      reliability: 0.9,
    },
    "src-plumbing": {
      id: "src-plumbing",
      type: "ESTIMATE",
      label: "Medyna Plumbing selected/comparable estimate - $7,800",
      observedAt: dt,
      authority: 0.85,
      reliability: 0.85,
    },
    "src-trades": {
      id: "src-trades",
      type: "PM_INPUT",
      label:
        "Current trade assignments: Elizabeth masonry; Jason Bonham electrical; Medina plumbing; Anthony Parker HVAC; Dylan Jasper paint",
      observedAt: dt,
      authority: 0.9,
      reliability: 0.85,
    },
    "src-brick-risk": {
      id: "src-brick-risk",
      type: "PM_INPUT",
      label:
        "Brick veneer matching discrepancy / Lee Block match task not verified; quote requires refresh",
      observedAt: dt,
      authority: 0.92,
      reliability: 0.9,
    },
    "src-material-quotes": {
      id: "src-material-quotes",
      type: "MATERIAL_ORDER",
      label:
        "Builders Choice / Lee material quotes and documented package contents; some quotes expired and require refresh",
      observedAt: dt,
      authority: 0.85,
      reliability: 0.78,
    },
  };
  const activities = {
    masonry: {
      id: "masonry",
      name: "CMU foundation walls",
      phase: "Foundation",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-masonry-calendar"],
      },
      constraintIds: ["masonry-material", "masonry-trade"],
      sourceIds: ["src-plans", "src-scope", "src-dashboard"],
    },
    structural_release: {
      id: "structural_release",
      name: "CMU structural release / anchors / elevations",
      phase: "Foundation",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 1,
        conservative: 2,
        sourceIds: ["src-plans", "src-scope", "src-engineering"],
      },
      constraintIds: ["structural-release-verify"],
      sourceIds: ["src-plans", "src-scope", "src-engineering"],
    },
    structural_reconcile: {
      id: "structural_reconcile",
      name: "Plan / LVL engineering reconciliation",
      phase: "Framing Readiness",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 1,
        conservative: 2,
        sourceIds: ["src-plans", "src-engineering"],
      },
      constraintIds: ["engineering-reconcile"],
      sourceIds: ["src-plans", "src-engineering", "src-dashboard"],
    },
    building_delivery: {
      id: "building_delivery",
      name: "Walls and subfloor package delivery",
      phase: "Procurement",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 1,
        conservative: 1,
        sourceIds: ["src-building-package"],
      },
      constraintIds: ["building-delivery-ready"],
      sourceIds: ["src-building-package", "src-dashboard"],
    },
    framing: {
      id: "framing",
      name: "Structural framing + second-floor/loft system",
      phase: "Framing",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 7,
        likely: 9,
        conservative: 12,
        sourceIds: ["src-plans", "src-scope", "src-budget"],
      },
      constraintIds: ["framer-availability", "framing-material"],
      sourceIds: ["src-plans", "src-scope", "src-engineering", "src-budget"],
    },
    roof_procurement: {
      id: "roof_procurement",
      name: "Roof package selection / refresh / release",
      phase: "Procurement",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 2,
        conservative: 3,
        sourceIds: ["src-roof-action", "src-material-quotes"],
      },
      constraintIds: ["roof-action", "roof-vendor"],
      sourceIds: ["src-roof-action", "src-material-quotes"],
    },
    roofing: {
      id: "roofing",
      name: "Roof underlayment / shingles / flashings",
      phase: "Envelope",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 3,
        likely: 4,
        conservative: 6,
        sourceIds: ["src-scope", "src-material-quotes"],
      },
      constraintIds: ["roof-material"],
      sourceIds: ["src-scope", "src-material-quotes"],
    },
    opening_protection: {
      id: "opening_protection",
      name: "Weather protection at windows / service door / garage openings",
      phase: "Envelope",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 2,
        conservative: 3,
        sourceIds: ["src-scope"],
      },
      constraintIds: ["opening-protection-material"],
      sourceIds: ["src-scope", "src-material-quotes"],
    },
    dry_in_release: {
      id: "dry_in_release",
      name: "Weather dry-in release",
      phase: "Envelope",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 1,
        conservative: 2,
        sourceIds: ["src-scope"],
      },
      constraintIds: [],
      sourceIds: ["src-scope"],
    },
    windows_ext_doors: {
      id: "windows_ext_doors",
      name: "Windows and exterior service door install",
      phase: "Envelope",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-material-quotes"],
      },
      constraintIds: ["windows-doors-material"],
      sourceIds: ["src-scope", "src-material-quotes"],
    },
    brick_veneer: {
      id: "brick_veneer",
      name: "Brick veneer / soldier courses / quoins",
      phase: "Exterior",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 5,
        likely: 7,
        conservative: 10,
        sourceIds: ["src-scope", "src-brick-risk"],
      },
      constraintIds: ["brick-match", "brick-material"],
      sourceIds: ["src-scope", "src-brick-risk", "src-material-quotes"],
    },
    underslab_mep: {
      id: "underslab_mep",
      name: "Under-slab plumbing/electrical routing",
      phase: "MEP",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-plumbing"],
      },
      constraintIds: ["mep-routing"],
      sourceIds: ["src-scope", "src-plumbing"],
    },
    slab_prep: {
      id: "slab_prep",
      name: "Slab stone / vapor / reinforcement / concealed inspection",
      phase: "Concrete",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: ["slab-inspection"],
      sourceIds: ["src-scope", "src-budget"],
    },
    slab: {
      id: "slab",
      name: "Garage and mower-storage slab pour / finish / cure release",
      phase: "Concrete",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: ["concrete-trade"],
      sourceIds: ["src-scope", "src-budget", "src-dashboard"],
    },
    electrical_rough: {
      id: "electrical_rough",
      name: "Electrical service and rough-in",
      phase: "MEP Rough",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 4,
        likely: 6,
        conservative: 9,
        sourceIds: ["src-scope", "src-trades"],
      },
      constraintIds: ["electrical-trade"],
      sourceIds: ["src-scope", "src-trades"],
    },
    plumbing_rough: {
      id: "plumbing_rough",
      name: "Half-bath plumbing rough-in",
      phase: "MEP Rough",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 3,
        likely: 4,
        conservative: 7,
        sourceIds: ["src-scope", "src-plumbing"],
      },
      constraintIds: ["plumbing-trade"],
      sourceIds: ["src-scope", "src-plumbing", "src-trades"],
    },
    hvac_rough: {
      id: "hvac_rough",
      name: "Multi-zone mini-split rough-in / lines / condensate",
      phase: "MEP Rough",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 3,
        likely: 5,
        conservative: 8,
        sourceIds: ["src-scope", "src-hvac"],
      },
      constraintIds: ["hvac-trade", "hvac-equipment"],
      sourceIds: ["src-scope", "src-hvac", "src-trades"],
    },
    rough_inspection: {
      id: "rough_inspection",
      name: "MEP rough inspections",
      phase: "Inspection",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 2,
        conservative: 4,
        sourceIds: ["src-scope"],
      },
      constraintIds: ["inspection-ready"],
      sourceIds: ["src-scope"],
    },
    insulation: {
      id: "insulation",
      name: "Insulation and air sealing",
      phase: "Close-In",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope"],
      },
      constraintIds: ["insulation-trade"],
      sourceIds: ["src-scope", "src-dashboard"],
    },
    drywall_hang: {
      id: "drywall_hang",
      name: "Drywall hang",
      phase: "Close-In",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 3,
        likely: 4,
        conservative: 6,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: ["drywall-trade"],
      sourceIds: ["src-scope", "src-budget"],
    },
    drywall_finish: {
      id: "drywall_finish",
      name: "Drywall tape / finish / sand",
      phase: "Close-In",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 4,
        likely: 6,
        conservative: 9,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: [],
      sourceIds: ["src-scope", "src-budget"],
    },
    prime_paint: {
      id: "prime_paint",
      name: "Prime and interior paint",
      phase: "Finishes",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 4,
        likely: 6,
        conservative: 9,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: ["paint-trade"],
      sourceIds: ["src-scope", "src-budget", "src-trades"],
    },
    finish_carpentry: {
      id: "finish_carpentry",
      name: "Interior doors / trim / stair finish / vanity setting",
      phase: "Finishes",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 4,
        likely: 6,
        conservative: 9,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: ["finish-carpentry-trade"],
      sourceIds: ["src-scope", "src-budget"],
    },
    flooring: {
      id: "flooring",
      name: "Second-floor flooring / transitions / stair finish",
      phase: "Finishes",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-budget"],
      },
      constraintIds: ["flooring-trade"],
      sourceIds: ["src-scope", "src-budget"],
    },
    half_bath_finish: {
      id: "half_bath_finish",
      name: "Half-bath vanity / top / fixtures / mirror / accessories",
      phase: "Finishes",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-plumbing"],
      },
      constraintIds: ["bath-finish-materials"],
      sourceIds: ["src-scope", "src-plumbing"],
    },
    garage_doors: {
      id: "garage_doors",
      name: "Overhead garage doors / openers / controls",
      phase: "Exterior",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope"],
      },
      constraintIds: ["garage-door-package"],
      sourceIds: ["src-scope", "src-budget"],
    },
    electrical_final: {
      id: "electrical_final",
      name: "Electrical trim / devices / lighting / testing",
      phase: "MEP Final",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope", "src-trades"],
      },
      constraintIds: [],
      sourceIds: ["src-scope", "src-trades"],
    },
    plumbing_final: {
      id: "plumbing_final",
      name: "Plumbing fixtures / trim / testing",
      phase: "MEP Final",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 2,
        conservative: 3,
        sourceIds: ["src-scope", "src-plumbing"],
      },
      constraintIds: [],
      sourceIds: ["src-scope", "src-plumbing"],
    },
    hvac_startup: {
      id: "hvac_startup",
      name: "HVAC startup / commissioning",
      phase: "MEP Final",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 2,
        conservative: 3,
        sourceIds: ["src-scope", "src-hvac"],
      },
      constraintIds: [],
      sourceIds: ["src-scope", "src-hvac"],
    },
    exterior_closeout: {
      id: "exterior_closeout",
      name: "Exterior trim / caulk / gutters / weatherproof closeout",
      phase: "Exterior",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 3,
        likely: 4,
        conservative: 6,
        sourceIds: ["src-scope"],
      },
      constraintIds: [],
      sourceIds: ["src-scope"],
    },
    final_grading_cleanup: {
      id: "final_grading_cleanup",
      name: "Final grading / lawn restoration / cleanup",
      phase: "Closeout",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 2,
        likely: 3,
        conservative: 5,
        sourceIds: ["src-scope"],
      },
      constraintIds: [],
      sourceIds: ["src-scope"],
    },
    final_inspection: {
      id: "final_inspection",
      name: "Final inspections / punch release",
      phase: "Closeout",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 2,
        conservative: 4,
        sourceIds: ["src-scope"],
      },
      constraintIds: ["final-inspection"],
      sourceIds: ["src-scope"],
    },
    homeowner_walkthrough: {
      id: "homeowner_walkthrough",
      name: "Systems demonstration / homeowner walkthrough / closeout package",
      phase: "Closeout",
      state: "NOT_STARTED" as const,
      duration: {
        optimistic: 1,
        likely: 1,
        conservative: 2,
        sourceIds: ["src-scope"],
      },
      constraintIds: [],
      sourceIds: ["src-scope"],
    },
  };
  const constraints = {
    "masonry-material": {
      id: "masonry-material",
      activityId: "masonry",
      type: "MATERIAL",
      label: "Correct CMU/block package on site and verified",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-dashboard", "src-material-quotes"],
      verification: "UNVERIFIED" as const,
    },
    "masonry-trade": {
      id: "masonry-trade",
      activityId: "masonry",
      type: "TRADE_AVAILABILITY",
      label: "Masonry crew mobilization after stale Aug 24 target",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-masonry-calendar", "src-trades"],
      verification: "UNVERIFIED" as const,
    },
    "structural-release-verify": {
      id: "structural-release-verify",
      activityId: "structural_release",
      type: "INFORMATION",
      label: "Anchor / elevation / bearing conditions field-verified",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-engineering", "src-dashboard"],
      verification: "UNVERIFIED" as const,
    },
    "engineering-reconcile": {
      id: "engineering-reconcile",
      activityId: "structural_reconcile",
      type: "INFORMATION",
      label: "Plan/LVL/post reconciliation status",
      state: "STALE_REVERIFY",
      hard: true,
      readiness: w("2026-08-26", "2026-08-27", "2026-08-28"),
      sourceIds: ["src-plans", "src-engineering", "src-dashboard"],
      verification: "STALE_REVERIFY" as const,
    },
    "building-delivery-ready": {
      id: "building-delivery-ready",
      activityId: "building_delivery",
      type: "MATERIAL",
      label: "Walls/subfloor delivery Aug 28",
      state: "COMMITTED",
      hard: true,
      readiness: w("2026-08-28", "2026-08-28", "2026-08-28"),
      sourceIds: ["src-building-package"],
      verification: "PM_CONFIRMED" as const,
    },
    "framer-availability": {
      id: "framer-availability",
      activityId: "framing",
      type: "TRADE_AVAILABILITY",
      label: "Framer mobilization",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-dashboard", "src-budget"],
      verification: "UNVERIFIED" as const,
    },
    "framing-material": {
      id: "framing-material",
      activityId: "framing",
      type: "MATERIAL",
      label:
        "Walls/subfloor/LVL framing package received, counted, undamaged, staged",
      state: "UNVERIFIED",
      hard: true,
      readiness: w("2026-08-28", "2026-08-28", "2026-08-31"),
      sourceIds: ["src-building-package", "src-engineering"],
      verification: "UNVERIFIED" as const,
    },
    "roof-action": {
      id: "roof-action",
      activityId: "roof_procurement",
      type: "INFORMATION",
      label: "Roof vendor analysis / contact Tony on Aug 26",
      state: "COMMITTED",
      hard: false,
      readiness: w("2026-08-26", "2026-08-26", "2026-08-26"),
      sourceIds: ["src-roof-action"],
      verification: "PM_CONFIRMED" as const,
    },
    "roof-vendor": {
      id: "roof-vendor",
      activityId: "roof_procurement",
      type: "INFORMATION",
      label: "Roof vendor/package decision and release",
      state: "UNVERIFIED",
      hard: true,
      readiness: w("2026-08-26", "2026-08-27", "2026-08-28"),
      sourceIds: ["src-roof-action", "src-material-quotes"],
      verification: "UNVERIFIED" as const,
    },
    "roof-material": {
      id: "roof-material",
      activityId: "roofing",
      type: "MATERIAL",
      label: "Roof package refreshed, ordered and available",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-material-quotes", "src-roof-action"],
      verification: "UNVERIFIED" as const,
    },
    "opening-protection-material": {
      id: "opening-protection-material",
      activityId: "opening_protection",
      type: "MATERIAL",
      label: "Temporary/permanent opening protection available",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-scope", "src-material-quotes"],
      verification: "UNVERIFIED" as const,
    },
    "windows-doors-material": {
      id: "windows-doors-material",
      activityId: "windows_ext_doors",
      type: "MATERIAL",
      label:
        "Window/service-door package availability and opening counts verified",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-material-quotes", "src-scope"],
      verification: "UNVERIFIED" as const,
    },
    "brick-match": {
      id: "brick-match",
      activityId: "brick_veneer",
      type: "MATERIAL",
      label: "Brick veneer match approved against existing residence",
      state: "BLOCKED",
      hard: true,
      sourceIds: ["src-brick-risk", "src-scope"],
      verification: "UNVERIFIED" as const,
    },
    "brick-material": {
      id: "brick-material",
      activityId: "brick_veneer",
      type: "MATERIAL",
      label: "Lee masonry material quote refreshed / package released",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-brick-risk", "src-material-quotes"],
      verification: "UNVERIFIED" as const,
    },
    "mep-routing": {
      id: "mep-routing",
      activityId: "underslab_mep",
      type: "INFORMATION",
      label: "Under-slab plumbing/electrical routing field-confirmed",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-scope", "src-plumbing", "src-trades"],
      verification: "UNVERIFIED" as const,
    },
    "slab-inspection": {
      id: "slab-inspection",
      activityId: "slab_prep",
      type: "INSPECTION",
      label: "Required under-slab/concealed inspection release",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-scope"],
      verification: "UNVERIFIED" as const,
    },
    "concrete-trade": {
      id: "concrete-trade",
      activityId: "slab",
      type: "TRADE_AVAILABILITY",
      label: "Concrete crew remobilization after dry-in",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-dashboard", "src-budget"],
      verification: "CORROBORATED" as const,
    },
    "electrical-trade": {
      id: "electrical-trade",
      activityId: "electrical_rough",
      type: "TRADE_AVAILABILITY",
      label: "Jason Bonham electrical rough-in mobilization",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-trades"],
      verification: "CORROBORATED" as const,
    },
    "plumbing-trade": {
      id: "plumbing-trade",
      activityId: "plumbing_rough",
      type: "TRADE_AVAILABILITY",
      label: "Medina plumbing rough-in mobilization",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-trades", "src-plumbing"],
      verification: "CORROBORATED" as const,
    },
    "hvac-trade": {
      id: "hvac-trade",
      activityId: "hvac_rough",
      type: "TRADE_AVAILABILITY",
      label: "Anthony Parker HVAC rough-in mobilization",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-trades", "src-hvac"],
      verification: "CORROBORATED" as const,
    },
    "hvac-equipment": {
      id: "hvac-equipment",
      activityId: "hvac_rough",
      type: "MATERIAL",
      label: "Multi-zone HVAC equipment / route / condensate plan ready",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-hvac", "src-scope"],
      verification: "CORROBORATED" as const,
    },
    "inspection-ready": {
      id: "inspection-ready",
      activityId: "rough_inspection",
      type: "INSPECTION",
      label: "All rough trades inspection-ready and inspection slot confirmed",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-scope"],
      verification: "UNVERIFIED" as const,
    },
    "insulation-trade": {
      id: "insulation-trade",
      activityId: "insulation",
      type: "TRADE_AVAILABILITY",
      label: "Insulation trade quote / mobilization",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-dashboard"],
      verification: "UNVERIFIED" as const,
    },
    "drywall-trade": {
      id: "drywall-trade",
      activityId: "drywall_hang",
      type: "TRADE_AVAILABILITY",
      label: "Drywall crew mobilization",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-budget", "src-dashboard"],
      verification: "UNVERIFIED" as const,
    },
    "paint-trade": {
      id: "paint-trade",
      activityId: "prime_paint",
      type: "TRADE_AVAILABILITY",
      label: "Dylan Jasper painting mobilization",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-trades", "src-budget"],
      verification: "CORROBORATED" as const,
    },
    "finish-carpentry-trade": {
      id: "finish-carpentry-trade",
      activityId: "finish_carpentry",
      type: "TRADE_AVAILABILITY",
      label: "Finish carpentry labor mobilization",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-budget"],
      verification: "CORROBORATED" as const,
    },
    "flooring-trade": {
      id: "flooring-trade",
      activityId: "flooring",
      type: "TRADE_AVAILABILITY",
      label: "Flooring labor mobilization",
      state: "FORECASTED",
      hard: true,
      sourceIds: ["src-budget"],
      verification: "CORROBORATED" as const,
    },
    "bath-finish-materials": {
      id: "bath-finish-materials",
      activityId: "half_bath_finish",
      type: "MATERIAL",
      label: "Vanity/top/fixtures/mirror/accessories ready",
      state: "UNVERIFIED",
      hard: false,
      sourceIds: ["src-scope", "src-plumbing"],
      verification: "UNVERIFIED" as const,
    },
    "garage-door-package": {
      id: "garage-door-package",
      activityId: "garage_doors",
      type: "MATERIAL",
      label:
        "Double + single overhead door/openers package ordered and available",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-scope", "src-budget"],
      verification: "UNVERIFIED" as const,
    },
    "final-inspection": {
      id: "final-inspection",
      activityId: "final_inspection",
      type: "INSPECTION",
      label: "Final inspection availability",
      state: "UNVERIFIED",
      hard: true,
      sourceIds: ["src-scope"],
      verification: "UNVERIFIED" as const,
    },
  };
  const dependencies: Record<
    string,
    {
      id: string;
      active: true;
      predecessorId: string;
      successorId: string;
      type: string;
      lagWorkdays: number;
      hard: true;
      reason: string;
      sourceIds: string[];
    }
  > = {};
  const add = (
    id: string,
    predecessorId: string,
    successorId: string,
    type = "FINISH_TO_START",
    lagWorkdays = 0,
    reason = "Required construction sequence",
    sourceIds: string[] = ["src-scope"],
  ): void => {
    dependencies[id] = {
      id,
      active: true,
      predecessorId,
      successorId,
      type,
      lagWorkdays,
      hard: true,
      reason,
      sourceIds,
    };
  };
  add(
    "d01",
    "masonry",
    "structural_release",
    "FINISH_TO_START",
    0,
    "CMU walls must complete before anchor/elevation release",
    ["src-scope", "src-engineering"],
  );
  add(
    "d02",
    "structural_release",
    "framing",
    "FINISH_TO_START",
    0,
    "Framing bears on released CMU/anchors",
    ["src-plans", "src-scope"],
  );
  add(
    "d03",
    "structural_reconcile",
    "framing",
    "FINISH_TO_START",
    0,
    "LVL/post condition must be reconciled before framing",
    ["src-plans", "src-engineering"],
  );
  add(
    "d04",
    "building_delivery",
    "framing",
    "FINISH_TO_START",
    0,
    "Framing package must be received before mobilization",
    ["src-building-package"],
  );
  add(
    "d05",
    "framing",
    "roofing",
    "START_TO_START",
    6,
    "Roofing can start after sufficient roof framing release",
    ["src-scope"],
  );
  add(
    "d06",
    "roof_procurement",
    "roofing",
    "FINISH_TO_START",
    0,
    "Roof package must be released before install",
    ["src-roof-action", "src-material-quotes"],
  );
  add(
    "d07",
    "framing",
    "opening_protection",
    "START_TO_START",
    5,
    "Openings can be weather-protected as framing advances",
    ["src-scope"],
  );
  add(
    "d08",
    "roofing",
    "dry_in_release",
    "FINISH_TO_START",
    0,
    "Roof completion is required for dry-in release",
    ["src-scope"],
  );
  add(
    "d09",
    "opening_protection",
    "dry_in_release",
    "FINISH_TO_START",
    0,
    "Openings must be weather-protected for dry-in release",
    ["src-scope"],
  );
  add(
    "d10",
    "framing",
    "windows_ext_doors",
    "FINISH_TO_START",
    0,
    "Permanent openings follow completed structural framing",
    ["src-scope"],
  );
  add(
    "d11",
    "windows_ext_doors",
    "brick_veneer",
    "FINISH_TO_START",
    0,
    "Brick detailing requires opening geometry/flashing coordination",
    ["src-scope"],
  );
  add(
    "d12",
    "dry_in_release",
    "underslab_mep",
    "FINISH_TO_START",
    0,
    "Scope requires framing dried-in before slab sequence",
    ["src-scope"],
  );
  add(
    "d13",
    "underslab_mep",
    "slab_prep",
    "FINISH_TO_START",
    0,
    "Concealed MEP routing must release slab preparation",
    ["src-scope"],
  );
  add(
    "d14",
    "slab_prep",
    "slab",
    "FINISH_TO_START",
    0,
    "Prepared/inspected slab base releases pour",
    ["src-scope"],
  );
  add(
    "d15",
    "dry_in_release",
    "electrical_rough",
    "FINISH_TO_START",
    0,
    "Interior electrical rough follows dry-in",
    ["src-scope"],
  );
  add(
    "d16",
    "dry_in_release",
    "plumbing_rough",
    "FINISH_TO_START",
    0,
    "Interior plumbing rough follows dry-in",
    ["src-scope"],
  );
  add(
    "d17",
    "dry_in_release",
    "hvac_rough",
    "FINISH_TO_START",
    0,
    "HVAC rough follows dry-in",
    ["src-scope"],
  );
  add(
    "d18",
    "electrical_rough",
    "rough_inspection",
    "FINISH_TO_START",
    0,
    "Electrical rough must complete before combined rough inspection",
    ["src-scope"],
  );
  add(
    "d19",
    "plumbing_rough",
    "rough_inspection",
    "FINISH_TO_START",
    0,
    "Plumbing rough must complete before combined rough inspection",
    ["src-scope"],
  );
  add(
    "d20",
    "hvac_rough",
    "rough_inspection",
    "FINISH_TO_START",
    0,
    "HVAC rough must complete before combined rough inspection",
    ["src-scope"],
  );
  add(
    "d21",
    "rough_inspection",
    "insulation",
    "FINISH_TO_START",
    0,
    "Rough inspection release required before close-in",
    ["src-scope"],
  );
  add(
    "d22",
    "insulation",
    "drywall_hang",
    "FINISH_TO_START",
    0,
    "Insulation and air sealing precede drywall",
    ["src-scope"],
  );
  add(
    "d23",
    "slab",
    "drywall_hang",
    "FINISH_TO_START",
    0,
    "Garage slab must be released before garage drywall close-in",
    ["src-scope"],
  );
  add(
    "d24",
    "drywall_hang",
    "drywall_finish",
    "FINISH_TO_START",
    0,
    "Board hang precedes tape/finish",
    ["src-scope"],
  );
  add(
    "d25",
    "drywall_finish",
    "prime_paint",
    "FINISH_TO_START",
    0,
    "Finished drywall releases prime/paint",
    ["src-scope"],
  );
  add(
    "d26",
    "prime_paint",
    "finish_carpentry",
    "FINISH_TO_START",
    0,
    "Base paint releases finished carpentry",
    ["src-scope"],
  );
  add(
    "d27",
    "finish_carpentry",
    "flooring",
    "FINISH_TO_START",
    0,
    "Trim/stair substrate coordination precedes flooring closeout",
    ["src-scope"],
  );
  add(
    "d28",
    "finish_carpentry",
    "half_bath_finish",
    "FINISH_TO_START",
    0,
    "Vanity/trim readiness precedes half-bath finish",
    ["src-scope"],
  );
  add(
    "d29",
    "slab",
    "garage_doors",
    "FINISH_TO_START",
    0,
    "Finished/cured slab supports garage-door install access",
    ["src-scope"],
  );
  add(
    "d30",
    "framing",
    "garage_doors",
    "FINISH_TO_START",
    0,
    "Garage-door openings must be structurally complete",
    ["src-scope"],
  );
  add(
    "d31",
    "finish_carpentry",
    "electrical_final",
    "FINISH_TO_START",
    0,
    "Trim/paint surfaces must be ready for electrical devices/fixtures",
    ["src-scope"],
  );
  add(
    "d32",
    "half_bath_finish",
    "plumbing_final",
    "FINISH_TO_START",
    0,
    "Bath finish must be ready for plumbing trim/testing",
    ["src-scope"],
  );
  add(
    "d33",
    "electrical_final",
    "hvac_startup",
    "FINISH_TO_START",
    0,
    "HVAC startup requires final electrical power/disconnect",
    ["src-scope"],
  );
  add(
    "d34",
    "roofing",
    "exterior_closeout",
    "FINISH_TO_START",
    0,
    "Roof edge details precede exterior closeout",
    ["src-scope"],
  );
  add(
    "d35",
    "brick_veneer",
    "exterior_closeout",
    "FINISH_TO_START",
    0,
    "Brick veneer precedes exterior caulk/trim closeout",
    ["src-scope"],
  );
  add(
    "d36",
    "garage_doors",
    "exterior_closeout",
    "FINISH_TO_START",
    0,
    "Garage doors/openers are part of envelope closeout",
    ["src-scope"],
  );
  add(
    "d37",
    "exterior_closeout",
    "final_grading_cleanup",
    "FINISH_TO_START",
    0,
    "Exterior work should be substantially complete before final restoration",
    ["src-scope"],
  );
  add(
    "d38",
    "slab",
    "final_grading_cleanup",
    "FINISH_TO_START",
    0,
    "Concrete operations complete before final grading/cleanup",
    ["src-scope"],
  );
  add(
    "d39",
    "flooring",
    "final_inspection",
    "FINISH_TO_START",
    0,
    "Interior flooring/trim must be complete for final",
    ["src-scope"],
  );
  add(
    "d40",
    "plumbing_final",
    "final_inspection",
    "FINISH_TO_START",
    0,
    "Plumbing final must complete before final inspection",
    ["src-scope"],
  );
  add(
    "d41",
    "electrical_final",
    "final_inspection",
    "FINISH_TO_START",
    0,
    "Electrical final must complete before final inspection",
    ["src-scope"],
  );
  add(
    "d42",
    "hvac_startup",
    "final_inspection",
    "FINISH_TO_START",
    0,
    "HVAC startup/testing must complete before final inspection",
    ["src-scope"],
  );
  add(
    "d43",
    "final_grading_cleanup",
    "final_inspection",
    "FINISH_TO_START",
    0,
    "Closeout site conditions precede final inspection",
    ["src-scope"],
  );
  add(
    "d44",
    "final_inspection",
    "homeowner_walkthrough",
    "FINISH_TO_START",
    0,
    "Final inspection/punch release precedes homeowner closeout",
    ["src-scope"],
  );
  const conflicts = {
    "conf-plan-engineering": {
      id: "conf-plan-engineering",
      category: "PLAN_ENGINEERING",
      description:
        "Tradewalk plan set and newer LVL/post engineering must be reconciled before framing commitment.",
      activityIds: ["structural_reconcile", "framing"],
      sourceIds: ["src-plans", "src-engineering", "src-dashboard"],
      severity: "HIGH",
      status: "OPEN",
    },
    "conf-brick-match": {
      id: "conf-brick-match",
      category: "MATERIAL_SELECTION",
      description:
        "Brick veneer match task is not verified against the existing residence and the Lee material quote requires refresh.",
      activityIds: ["brick_veneer"],
      sourceIds: ["src-brick-risk", "src-material-quotes"],
      severity: "HIGH",
      status: "OPEN",
    },
  };
  const commercialSignals = {
    "sig-framing": {
      id: "sig-framing",
      kind: "ESTIMATE",
      activityIds: ["framing"],
      workPackage: "Rough carpentry labor",
      amount: 13500.72,
      currency: "USD",
      selected: true,
      scopeCoverage: "FULL",
      sourceIds: ["src-budget"],
    },
    "sig-building-material": {
      id: "sig-building-material",
      kind: "ESTIMATE",
      activityIds: ["building_delivery", "framing", "opening_protection"],
      workPackage: "Builders Choice multi-trade building package",
      amount: 17692.84,
      currency: "USD",
      selected: false,
      scopeCoverage: "PARTIAL",
      sourceIds: ["src-budget", "src-material-quotes"],
    },
    "sig-brick-material": {
      id: "sig-brick-material",
      kind: "ESTIMATE",
      activityIds: ["brick_veneer"],
      workPackage:
        "Lee Building Products brick/masonry materials - expired quote",
      amount: 12409.21,
      currency: "USD",
      selected: true,
      scopeCoverage: "PARTIAL",
      sourceIds: ["src-budget", "src-material-quotes"],
    },
    "sig-roof-material": {
      id: "sig-roof-material",
      kind: "ESTIMATE",
      activityIds: ["roof_procurement", "roofing"],
      workPackage: "Builders Choice shingles package - expired quote",
      amount: 2936.45,
      currency: "USD",
      selected: false,
      scopeCoverage: "PARTIAL",
      sourceIds: ["src-budget", "src-material-quotes"],
    },
    "sig-plumbing": {
      id: "sig-plumbing",
      kind: "ESTIMATE",
      activityIds: ["underslab_mep", "plumbing_rough", "plumbing_final"],
      workPackage: "Medina Plumbing",
      amount: 7800,
      currency: "USD",
      selected: true,
      scopeCoverage: "FULL",
      sourceIds: ["src-plumbing", "src-budget"],
    },
    "sig-hvac": {
      id: "sig-hvac",
      kind: "ESTIMATE",
      activityIds: ["hvac_rough", "hvac_startup"],
      workPackage: "Multi-zone mini-split",
      amount: 7366,
      currency: "USD",
      selected: true,
      scopeCoverage: "FULL",
      sourceIds: ["src-hvac"],
    },
    "sig-floor": {
      id: "sig-floor",
      kind: "ESTIMATE",
      activityIds: ["flooring"],
      workPackage: "Flooring labor",
      amount: 2700,
      currency: "USD",
      selected: true,
      scopeCoverage: "FULL",
      sourceIds: ["src-budget"],
    },
    "sig-paint": {
      id: "sig-paint",
      kind: "ESTIMATE",
      activityIds: ["prime_paint"],
      workPackage: "Painting labor",
      amount: 4000,
      currency: "USD",
      selected: true,
      scopeCoverage: "FULL",
      sourceIds: ["src-budget", "src-trades"],
    },
  };
  const workloadSignals = {
    "work-floor": {
      id: "work-floor",
      activityIds: ["flooring"],
      dimension: "AREA",
      value: 900,
      unit: "SF",
      label: "Documented flooring labor area",
      sourceIds: ["src-budget"],
    },
    "work-floor-joists": {
      id: "work-floor-joists",
      activityIds: ["framing"],
      dimension: "COUNT",
      value: 70,
      unit: "pieces",
      label: "Approximate 2x12 floor joist package count",
      sourceIds: ["src-building-package"],
    },
    "work-roof-rafters": {
      id: "work-roof-rafters",
      activityIds: ["framing", "roofing"],
      dimension: "COUNT",
      value: 97,
      unit: "pieces",
      label: "Documented roof framing members in material package",
      sourceIds: ["src-building-package"],
    },
  };
  const impactSeedActivityIds = Object.keys(activities);
  const bootstrapEvent = {
    id: "deboard-v091-baseline-evidence-2026-08-26",
    baseRevision: 0,
    projectId,
    type: "BASELINE_EVIDENCE",
    occurredAt: dt,
    receivedAt: dt,
    sourceIds: Object.keys(sources),
    verification: "PM_CONFIRMED" as const,
    impactSeedActivityIds,
    mutations: [],
    payload: {
      purpose: "v0.9.1 truth-semantics baseline",
      rule: "Calendar commitments are not actual starts; future deliveries are COMMITTED until field-verified; forecast dates remain distinct from production commitments.",
    },
    note: "Bootstrap provenance event. No live system is modified.",
  };
  return {
    projectId,
    revision: 1,
    name: "DeBoard - 227 Marengo Dr - v0.9.1 truth-semantics shadow",
    projectType:
      "Detached garage + mower storage + conditioned second-floor office/flex + half bath",
    timezone: "America/New_York",
    forecastAnchorDate: "2026-08-26",
    calendar: { workingWeekdays: [1, 2, 3, 4, 5], holidays: [] },
    sources,
    activities,
    constraints,
    dependencies,
    conflicts,
    commercialSignals,
    workloadSignals,
    eventLedger: [bootstrapEvent],
  };
}
